package regeltests;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import model.UnitTest;
import org.junit.Test;

@MPSLaunch
public class testTrial extends UnitTest {

  @Test
  public void _001() throws Throwable {
    UnitTest.test("InvoicePaymentTest.regeltests.test trial.001", "9183417899581685335", "9183417899581685370", "/home/steven/AlefProjects/ALEF-demo-trial", "r:c154ae24-313e-40a0-9f59-682c753bfd6c(regeltests)", myEnvironment);
  }
  @Test
  public void _003() throws Throwable {
    UnitTest.test("InvoicePaymentTest.regeltests.test trial.003", "9183417899581685335", "2513092667722227955", "/home/steven/AlefProjects/ALEF-demo-trial", "r:c154ae24-313e-40a0-9f59-682c753bfd6c(regeltests)", myEnvironment);
  }
  @Test
  public void _002() throws Throwable {
    UnitTest.test("InvoicePaymentTest.regeltests.test trial.002", "9183417899581685335", "2513092667722213375", "/home/steven/AlefProjects/ALEF-demo-trial", "r:c154ae24-313e-40a0-9f59-682c753bfd6c(regeltests)", myEnvironment);
  }

}
