package Services;

/*Generated by MPS */

import converter.impl.AbstractObjectModel;
import converter.model.domain.Enumeratie;

public class invoicepayment____ObjectModel extends AbstractObjectModel {
  @Override
  public String getName() {
    System.err.println("WARNING: " + getClass().getSimpleName() + ".getName() was called it used to return the namespacePrefix but returns the service name now. This might cause unexpected results. (ALEF-2693)");
    return "InvoicePayment";
  }

  @Override
  public String getServiceAcroniem() {
    return "rsinvoicepayment";
  }

  @Override
  public String getBlazeEntryPointFunctionName() {
    return "berekenInvoicepayment";
  }

  @Override
  public String getXmlNamespace() {
    return "http://www.belastingdienst.nl/InvoicepaymentBlazeBOM";
  }

  @Override
  public String getXsdFileName() {
    return "rsinvoicepayment/invoicepayment.xsd";
  }

  public invoicepayment____ObjectModel() {
    Enumeratie rol;
    Enumeratie actie;
    {
      rol = addDomein(new Enumeratie("rol"));
      rol.addValue("owner_2513092667722210269", "Owner");
      rol.addValue("builder_2513092667722210286", "Builder");
      rol.addValue("supplier_2513092667722210322", "Supplier");
      rol.addValue("architect_2513092667722210353", "Architect");
      rol.setDefault("onbekend");
    }
    {
      actie = addDomein(new Enumeratie("actie"));
      actie.addValue("niet_spUit_spTe_spBetalen_spFactuur_9183417899581682784", "NietUitTeBetalenFactuur");
      actie.addValue("in_spTermijnen_spBetalen_9183417899581682819", "InTermijnenBetalen");
      actie.addValue("volledig_spBetalen_9183417899581682867", "VolledigBetalen");
      actie.setDefault("onbekend");
    }

  }
}
